.\"  Copyright (c) 2007-2016, The CHICKEN Team
.\"  All rights reserved.
.\"
.\"  Redistribution and use in source and binary forms, with or without
.\"  modification, are permitted provided that the following conditions
.\"  are met:
.\"  1. Redistributions of source code must retain the above copyright
.\"     notice, this list of conditions and the following disclaimer.
.\"  2. Redistributions in binary form must reproduce the above copyright
.\"     notice, this list of conditions and the following disclaimer in the
.\"     documentation and/or other materials provided with the distribution.
.\"  3. The name of the authors may not be used to endorse or promote products
.\"     derived from this software without specific prior written permission.
.\"
.\"  THIS SOFTWARE IS PROVIDED BY THE AUTHORS ``AS IS'' AND ANY EXPRESS OR
.\"  IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\"  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\"  IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY DIRECT, INDIRECT,
.\"  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
.\"  NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\"  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\"  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\"  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
.\"  THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.\"
.Dd Mar 25, 2016
.Dt CSC 1
.Os
.Sh NAME
.Nm csc
.Nd driver program for the CHICKEN Scheme compiler
.Sh SYNOPSIS
.Nm
.Op Ar FILENAME \(ba OPTION ...
.Sh DESCRIPTION
.Nm
is a program that invokes the CHICKEN compiler and the host systems C compiler to generate
an executable from a Scheme source file or C files generated by CHICKEN.
.Pp
.Ar FILENAME
is a Scheme source file name with optional extension or a C/C++/Objective-C source,
object or library file name with extension.
.Ar OPTION
may be one of the following:
.Pp
General options:
.Bl -tag -width Ds
.It Fl h, Fl help
display usage text and exit
.It Fl v, Fl verbose
show compiler notes and tool-invocations
.It Fl vv
display information about translation progress
.It Fl vvv
display information about all compilation stages
.It Fl version
display Scheme compiler version and exit
.It Fl release
display release number and exit
.El
.Pp
File and pathname options:
.Bl -tag -width Ds
.It Fl o Ar FILENAME, Fl output-file Ar FILENAME
specifies target executable name
.It Fl I Ar PATHNAME, Fl include-path Ar PATHNAME
specifies alternative path for included files
.It Fl to-stdout
write compiler to stdout
.Po implies -t Pc
.It Fl s, Fl shared, Fl dynamic
generate dynamically loadable shared object file
.El
.Pp
Language options:
.Bl -tag -width Ds
.It Fl D, Fl D Ar SYMBOL, Fl feature Ar SYMBOL
register feature identifier
.It Fl no-feature Ar SYMBOL
disable builtin feature identifier
.It Fl c++
compile via a C++ source file
.Pq .cpp
.It Fl objc
compile via Objective-C source file
.Pq \&.m
.El
.Pp
Syntax related options:
.Bl -tag -width Ds
.It Fl i, Fl case-insensitive
don't preserve case of read symbols
.It Fl K, Fl keyword-style Ar STYLE
enable alternative keyword-syntax
.Po prefix, suffix or none Pc
.It Fl no-parentheses-synonyms
disables list delimiter synonyms
.It Fl no-symbol-escape
disables support for escaped symbols
.It Fl r5rs-syntax
disables the CHICKEN extensions to R5RS syntax
.It Fl compile-syntax
macros are made available at run-time
.It Fl j Ar MODULE, Fl emit-import-library Ar MODULE
write compile-time module information into separate file
.It Fl J, Fl emit-all-import-libraries
emit import-libraries for all defined modules
.It Fl no-module-registration
do not generate module registration code
.It Fl no-compiler-syntax
disable expansion of compiler-macros
.It Fl M, Fl module
wrap compiled code into implicit module
.El
.Pp
Translation options:
.Bl -tag -width Ds
.It Fl x, Fl explicit-use
do not use units
.Sq library
and
.Sq eval
by default
.It Fl P, Fl check-syntax
stop compilation after macro-expansion
.It Fl A, Fl analyze-only
stop compilation after first analysis pass
.El
.Pp
Debugging options:
.Bl -tag -width Ds
.It Fl w, Fl no-warnings
disable warnings
.It Fl d0, Fl d1, Fl d2, Fl debug-level Ar NUMBER
set level of available debugging information
.It Fl no-trace
disable rudimentary debugging information
.It Fl profile
executable emits profiling information
.It Fl accumulate-profile
executable emits profiling information in append mode
.It Fl profile-name Ar FILENAME
name of the generated profile information file
.It Fl types Ar FILENAME
load additional type database
.El
.Pp
Optimization options:
.Bl -tag -width Ds
.It Fl O, Fl O0, Fl O1, Fl O2, Fl O3, Fl O4, Fl O5, Fl optimize-level Ar NUMBER
enable certain sets of optimization options
.It Fl optimize-leaf-routines
enable leaf routine optimization
.It Fl no-usual-integrations
standard procedures may be redefined
.It Fl u, Fl unsafe
disable safety checks
.It Fl local
assume globals are only modified in current file
.It Fl b, Fl block
enable block-compilation
.It Fl disable-interrupts
disable interrupts in compiled code
.It Fl f, Fl fixnum-arithmetic
assume all numbers are fixnums
.It Fl disable-stack-overflow-checks
disables detection of stack-overflows
.It Fl inline
enable inlining
.It Fl inline-limit Ar LIMIT
set inlining threshold
.It Fl inline-global
enable cross-module inlining
.It Fl specialize
perform type-based specialization of primitive calls
.It Fl oi Ar FILENAME, Fl emit-inline-file Ar FILENAME
generate file with globally inlinable procedures
.Po implies Fl inline Fl local Pc
.It Fl consult-inline-file Ar FILENAME
explicitly load inline file
.It Fl ot Ar FILENAME, Fl emit-type-file Ar FILENAME
write type-declaration information into file
.It Fl no-argc-checks
disable argument count checks
.It Fl no-bound-checks
disable bound variable checks
.It Fl no-procedure-checks
disable procedure call checks
.It Fl no-procedure-checks-for-usual-bindings
disable procedure call checks only for usual bindings
.It Fl no-procedure-checks-for-toplevel-bindings
disable procedure call checks for toplevel bindings
.It Fl strict-types
assume variable do not change their type
.It Fl clustering
combine groups of local procedures into dispatch loop
.It Fl lfa2
perform additional lightweight flow-analysis pass
.El
.Pp
Configuration options:
.Bl -tag -width Ds
.It Fl unit Ar NAME
compile file as a library unit
.It Fl uses Ar NAME
declare library unit as used.
.It Fl heap-size Ar NUMBER
specifies heap-size of compiled executable
.It Fl nursery Ar NUMBER Fl stack-size Ar NUMBER
specifies nursery size of compiled executable
.It Fl X Ar FILENAME, Fl extend Ar FILENAME
load file before compilation commences
.It Fl prelude Ar EXPRESSION
add expression to beginning of source file
.It Fl postlude Ar EXPRESSION
add expression to end of source file
.It Fl prologue Ar FILENAME
include file before main source file
.It Fl epilogue Ar FILENAME
include file after main source file
.It Fl e, Fl embedded
compile as embedded
.Po don't generate
.Sq Fn main
.Pc
.It Fl gui
compile as GUI application
.It Fl R Ar NAME, Fl require-extension Ar NAME
require extension and import in compiled code
.It Fl dll, Fl library
compile multiple units into a dynamic library
.It Fl deploy
deploy self-contained application bundle
.El
.Pp
Options to other passes:
.Bl -tag -width Ds
.It Fl C Ar OPTION
pass option to C compiler
.It Fl L Ar OPTION
pass option to linker
.It Fl I Ns Ar <DIR>
pass
.Dq -I<DIR>
to C compiler
.Po add include path Pc
.It Fl L Ns Ar <DIR>
pass
.Dq -L<DIR>
to linker
.Po add library path Pc
.It Fl k
keep intermediate files
.It Fl c
stop after compilation to object files
.It Fl t
stop after translation to C
.It Fl cc Ar COMPILER
select other C compiler than the default
.It Fl cxx Ar COMPILER
select other C++ compiler than the default
.It Fl ld Ar COMPILER
select other linker than the default
.It Fl l Ns Ar LIBNAME
link with given library
.Po
.Sq libLIBNAME
on UNIX,
.Sq LIBNAME.lib
on Windows
.Pc
.It Fl static-libs
link with static CHICKEN libraries
.It Fl static
generate completely statically linked executable
.It Fl F Ns Ar <DIR>
pass
.Dq -F<DIR>
to C compiler
.Po add framework header path on Mac OS X Pc
.It Fl framework Ar NAME
passed to linker on Mac OS X
.It Fl rpath Ar PATHNAME
add directory to runtime library search path
.It Fl Wl,...
pass linker options
.It Fl strip
strip resulting binary
.El
.Pp
Inquiry options:
.Bl -tag -width Ds
.It Fl home
show home-directory
.Po where support files go Pc
.It Fl cflags
show required C-compiler flags and exit
.It Fl ldflags
show required linker flags and exit
.It Fl libs
show required libraries and exit
.It Fl cc-name
show name of default C compiler used
.It Fl cxx-name
show name of default C++ compiler used
.It Fl ld-name
show name of default linker used
.It Fl dry-run
just show commands executed, don't run them
.Po implies Sq Fl v
.Pc .
.El
.Pp
Obscure options:
.Bl -tag -width Ds
.It Fl debug Ar MODES
display debugging output for the given modes
.It Fl compiler Ar PATHNAME
use other compiler than default
.Sq chicken
.It Fl raw
do not generate implicit init- and exit code
.It Fl emit-external-prototypes-first
emit prototypes for callbacks before foreign declarations
.It Fl ignore-repository
do not refer to repository for extensions
.It Fl keep-shadowed-macros
do not remove shadowed macro
.It Fl host
compile for host when configured for cross-compiling
.It Fl private-repository
load extensions from executable path
.It Fl deployed
link support file to be used from a deployed executable
.Po sets
.Sq rpath
accordingly, if supported on this platform
.Pc
.It Fl no-elevation
embed manifest on Windows to supress elevation warnings for programs named
.Sq install
or
.Sq setup
.El
.Pp
Options can be collapsed if unambiguous, so
.Dq -vkfO
is the same as
.Dq -v -k -fixnum-arithmetic -optimize .
.Sh ENVIRONMENT
Following environment variables change the behaviour of
.Nm
.Bl -tag -width CHICKEN_PREFIX
.It Ev CSC_OPTIONS
Can hold default options that should be passed to every invocation of
.Nm
.It Ev CHICKEN_PREFIX
The installation prefix where CHICKEN Scheme and its support files and
libraries are located. Defaults to the installation time prefix given
when configuring the system.
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr chicken 1 ,
.Xr chicken-bug 1
.Pp
More information can be found in the
.Lk http://wiki.call-cc.org/manual/index "CHICKEN User's Manual".
.Sh AUTHORS
.An The CHICKEN Team
.Sh BUGS
Submit bug reports by e-mail to
.Mt chicken-janitors@nongnu.org ,
preferrably using the
.Xr chicken-bug 1
tool.
